# Build numbering format
name: $(BuildID)

trigger:
  branches:
    include:
      - master
      - feat/*


pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      echo "Hello from '/' root folder."
