# Build numbering format
name: $(BuildID)

trigger:
  branches:
    include:
      - master
      - feat/*


pool:
  vmImage: 'ubuntu-latest'

stages:


- template: service-a/azure-pipelines-a.yml
  parameters:
    name: test
- template: service-b/azure-pipelines-b.yml
  parameters:
    name: Btest
    working-dir: 'service-b/'
