parameters:  
  name: BDefault


stages:
- stage: Build  
  jobs:
  - job: TEST_JOB_${{ parameters.name }}
    steps:
    - script: echo "Hello from 'service-b'"

    - script: npm install
      workingDirectory: ${{ parameters.working-dir }}

    - script: npm run chalk
      workingDirectory: ${{ parameters.working-dir }}
